# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.monitoring as module_0


def test_case_0():
    none_type_0 = None
    none_type_1 = None
    bool_gauge_cell_0 = module_0.BoolGaugeCell(none_type_0)
    bool_gauge_cell_0.set(none_type_1)
