# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.monitoring as module_0


def test_case_0():
    none_type_0 = None
    sampler_cell_0 = module_0.SamplerCell(none_type_0)
    sampler_cell_0.value()
