# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.profiler.profiler_v2 as module_0


def test_case_0():
    none_type_0 = None
    module_0.start(none_type_0, none_type_0)
