# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.data.experimental.service.server_lib as module_0


def test_case_0():
    module_0.DispatchServer()
    none_type_0 = None
    module_0.DispatchServer(start=none_type_0)
