# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.data.experimental.service.server_lib as module_0


def test_case_0():
    none_type_0 = None
    dispatch_server_0 = module_0.DispatchServer(start=none_type_0)
    dispatch_server_0.join()
    module_0.WorkerConfig(*none_type_0, **dispatch_server_0)
