# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.framework.c_api_util as module_0


def test_case_0():
    api_def_map_0 = module_0.ApiDefMap()
    var_0 = api_def_map_0.__repr__()
    api_def_map_0.get_api_def(var_0)
