# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.framework.kernels as module_0


def test_case_0():
    none_type_0 = None
    module_0.get_registered_kernels_for_op(none_type_0)
