# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.compiler.tf2xla.ops.gen_xla_ops as module_0


def test_case_0():
    module_0.xla_replica_id()
