# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.client._pywrap_tf_session as module_0


def test_case_0():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0]
    module_0.PyOperation(*list_0)
