# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import numpy as module_0
import tensorflow.python.client._pywrap_tf_session as module_1


def test_case_0():
    var_0 = module_0.geterr()
    module_1.PyTensor(*var_0, **var_0)
