# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.context as module_0


def test_case_0():
    var_0 = module_0.enable_xla_sharding_for_resource_variables()
    module_0.add_c_function(var_0)
