# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.context as module_0
import tensorflow.python.data.experimental.ops.random_ops as module_1


def test_case_0():
    var_0 = module_0.get_device_name()
    module_1.RandomDatasetV2(rerandomize_each_iteration=var_0)
    module_0.check_alive(var_0)
