# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tokenize as module_0
import tensorflow.python.eager.context as module_1


def test_case_0():
    var_0 = module_0.maybe()
    none_type_0 = None
    context_0 = module_1.Context(device_policy=none_type_0)
    context_0.delete_config_key_value(var_0)
