# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.remote as module_0
import tensorflow.python.ops.math_ops as module_1


def test_case_0():
    str_0 = "bW5a ]"
    module_0.connect_to_remote_host(str_0)
    module_1.to_int64(str_0)
