# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.framework.config as module_0


def test_case_0():
    var_0 = module_0.disable_mlir_bridge()
    module_0.get_memory_info(var_0)
