# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.record as module_0


def test_case_0():
    variable_watcher_0 = module_0.VariableWatcher()
    variable_watcher_0.watched_variables()
