# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.executor as module_0


def test_case_0():
    none_type_0 = None
    executor_0 = module_0.Executor(none_type_0)
    executor_0.clear_error()
