# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.tape as module_0


def test_case_0():
    list_0 = []
    tape_0 = module_0.Tape(list_0)
    module_0.push_tape(tape_0)
    module_0.variable_accessed(tape_0)
