# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.tape as module_0


def test_case_0():
    str_0 = "*/"
    tape_0 = module_0.Tape(str_0)
    tape_0.watched_variables()
