# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.profiler_client as module_0


def test_case_0():
    int_0 = -625
    none_type_0 = None
    module_0.monitor(none_type_0, int_0, int_0)
