# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.eager.profiler_client as module_0


def test_case_0():
    none_type_0 = None
    bool_0 = True
    module_0.start_tracing(none_type_0, none_type_0, bool_0)
