# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import tensorflow.python.data.ops.random_op as module_0
import tensorflow.compiler.tf2xla.ops.gen_xla_ops as module_1


def test_case_0():
    random_dataset_0 = module_0._RandomDataset()
    module_1.xla_replica_id(random_dataset_0)
